---
title: "Descriptives of metadata"
author: "Monica Alexander"
date: "August 23, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Calculate a few summary descriptives of the data that we have based on the metadata in the csv files. 

```{r, message=FALSE}
#library(plyr)
library(tidyverse)
library(lubridate)

# read in all the meta data acsv files
csv_files <- paste0("../data/raw/", list.files(path = "../data/raw",pattern = ".*.csv"))

meta_df <- c()

for(i in 1:length(csv_files)){
  this_meta <- read_csv(csv_files[i])
  meta_df <- bind_rows(meta_df, this_meta )
}
rm(this_meta)
md <- meta_df
rm(meta_df)
```
Number of articles by year:

```{r}

# number of articles by year
md %>% 
  group_by(year) %>% 
  summarise(n = n()) %>%
  ggplot(aes(year, n)) + 
  geom_line() + geom_point() + ggtitle("Number of articles per year")+ theme_bw()
ggsave("../plots/number_year.pdf", height = 7, width =10)
```

Plot number of articles by source and year:

```{r}
# plot number of articles by source and year

source_year <- md %>% 
  group_by(year, pubtitle) %>% 
  summarise(n = n())

ggplot(source_year, aes(year, n, color = pubtitle)) + 
  geom_point() + geom_line() + 
  scale_x_continuous(breaks=seq(2008,2017, by =2))+ 
  theme_minimal() + scale_color_brewer(palette="Set1", name = "Source") +
  ylab("Number") + xlab("Year") + ggtitle("Number of articles by year and source") 
ggsave("../plots/source_year.pdf", height = 7, width =10)

write_csv(source_year, path = "../tables/source_year.csv")
```

Fixing up date column. May be useful later. 

```{r}
# make publication date consistent

md$date_char <- NA

for(i in 1:nrow(md)){
  if(grepl(",", md$pubdate[i])){
    split_date <- strsplit(md$pubdate[i], split = " ")[[1]]
    dt <- paste(gsub(",", "", split_date[2]), split_date[1], substr(split_date[3], 3, 4), sep = "-")
  }
  else{
    dt <- md$pubdate[i]
  }
  md$date_char[i] <- dt
}

md$date <- dmy(md$date_char)

# this is not that useful
# but note 9/11 coverage 
md %>% group_by(date, pubtitle) %>%
  summarise(Number = n()) %>% 
  arrange(-Number) %>% filter(Number > 5)

```

Look at subject classifications

```{r}
# look at subjects of articles
subjects_list <- strsplit(md$subjectTerms, split = " , ")
subjects_vec <- unlist(subjects_list)
subject_counts <- sort(table(subjects_vec), decreasing = T)
head(subject_counts, 20)
write_csv(as.data.frame(subject_counts), path = "../tables/subjects_counts.csv")
```

Subjects by source type:

```{r}
sources <- unique(md$pubtitle)
subject_all_sources <- c()
for(i in 1:length(sources)){
  subjects_source <- unlist(subjects_list[which(md$pubtitle==sources[i])])
  subjects_source_count <- sort(table(subjects_source), decreasing = T)
  subjects_source_df <- as.data.frame(subjects_source_count)
  subjects_source_df$source <- sources[i]
  subject_all_sources <- rbind(subject_all_sources, subjects_source_df)
}

# calculate proportion 
subject_all_sources <- subject_all_sources %>% 
  group_by(source) %>% 
  mutate(prop = Freq/sum(Freq))

subject_all_sources %>% 
  group_by(source) %>% 
  top_n(n= 5)

write_csv(subject_all_sources, path = "../tables/subject_source.csv")
```

Subjects by year:

```{r}
years <- unique(md$year)
subject_all_years <- c()
for(i in 1:length(years)){
  subjects_year <- unlist(subjects_list[which(md$year==years[i])])
  subjects_year_count <- sort(table(subjects_year), decreasing = T)
  subjects_year_df <- as.data.frame(subjects_year_count)
  subjects_year_df$year <- years[i]
  subject_all_years <- rbind(subject_all_years, subjects_year_df)
}

# calculate proportion 
subject_all_years <- subject_all_years %>% 
  group_by(year) %>% 
  mutate(prop = Freq/sum(Freq))

write_csv(subject_all_years, path = "../tables/subject_year.csv")
```

```{r}
top5 <- subject_all_years %>% 
  group_by(year) %>% 
  top_n(n= 5)

subs <- as.character(unique(top5$subjects_year))

big_subs <- subject_all_years %>% filter(subjects_year %in% subs)

ggplot(big_subs, aes(year, prop, color = subjects_year)) + 
  geom_point() + geom_line() + 
  scale_x_continuous(breaks=seq(2008,2017, by =2))+ 
  theme_minimal() + scale_color_discrete(name = "Subject") +
  ylab("Propotion") + xlab("Year") + ggtitle("Proportion of articles mentioning subject") 
ggsave("../plots/subject_year.pdf", height = 7, width =10)
```
Do some bar plots by year

```{r}
pd <- subject_all_years %>%
  group_by(year) %>%
  top_n(10, wt = Freq) %>%
  ungroup() %>%
  arrange(year, Freq) %>%
  mutate(order=row_number())


  ggplot(pd, aes(order, Freq)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~year, scales = "free") +
  labs(y = "No. articles",
       x = NULL) +
    scale_x_continuous(
      breaks = pd$order,
      labels = pd$subjects_year,
      expand = c(0,0)
    ) +
  coord_flip()+
    ggtitle("Top subjects by year")
  ggsave("../plots/subject_year_barplot.pdf", height = 10, width = 12)
```

